{% set version = '0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-docopt
  version: {{ version|replace("-", "_") }}

source:
  fn: docopt_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/docopt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/docopt/docopt_{{ version }}.tar.gz
  sha256: 933558792e7a55a3e59df494e22b79ba063121d198274b88b9a8eed9c796db24

build:
  noarch: generic
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('docopt')"           # [not win]
    - "\"%R%\" -e \"library('docopt')\""  # [win]

about:
  home: https://github.com/docopt/docopt.R
  license: MIT
  summary: Define a command-line interface by just giving it a description in the specific format.
  license_family: MIT

extra:
  recipe-maintainers:
    - dpryan79
    - jdblischak
    - johanneskoester
    - bgruening
    - daler
