# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DcZCIBZZyV8fGvWZnYWd7P8fjdp0HsRvCrK7H6m4u+HKoSqavqzEK7j/RHr+FhTsm67twU++c3pQdyYTywL9XIBqTwtZPKxA5jkYJqeaDQohzlGeMDGcdmifCVXg2+Mnu8KcRz6tLhDkpxA9US14h3DZ3S8hCGUrwqI1UqBBMZhs5X9wrdnXfVu/wNtx9jPAhm1eoTQRs7Bh5HU/cukLjmCCruNMyZBr9DMT8JZ9m5orrxmg2WNTh9yt5vUmIqMn7bSjnCMThdjGZbGILKh1cUSGx7zphEYMXLWFFGJ3EkviW0xfBiA4yrMK/TBOWPUg1xRUk5knDbNxhsLspxELNMc4Sc+3tr8UFhW8FneEDbgrh4eTJvBf14iD4XoiyvvYHY1wmvY7WObtEEfaPwmndMlOzFdtrdE5agiX3GKkNfqlNtnuRdqchzaerwVctfyjs2IjOj2B8+PoakryR42dDCmqAREWHKGfCowLNk19ASieIx1jBs+OBJq+KN2R4+dW5vy0RfaTtje1F4SLlL5lJTIaGUGgZiiYrCxnjypzzzvkPB/FobJQHbL8NRd/C3zcUCm+8b7lJ5zqcFwddjYw2qiaTG1X4Ohh5DHY+qpdmVB7gC3mjCGaZ/JuM/KXKGvB2pI/W6SgbktMznD4YWRcU+lEEUV7/oZK095Vz4IIl/c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
