appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: hqdg3WcpZboUS7OnFmqR7yhEVSsGyJYK65dd3+IbV1wupJqMzC/7UNmCgeXh67NHzI3wZha2dWR6Pkd6dzIjpIcpZgM4I6UZDBnkQlgBcpXPurFTArMolbWo16vjFsdqb8Y0fRJMOALKRPqzcmYfWMvuGaUmBSYi+0Quu6nDrmO6YcdwjU7naxGfrJ0eqV/v1eIPfIUjer1EMEULKkdHbQmi9YrLYYTNea9tb7COcbX8dGesAoqOf70KaBzvaf94UB6qgjKLiSu6RcAOtc+4v1Lz2FdCWmXK0w6yAu0J4Cy4ejW0BP4JQJnrpQhmPfPb66TzG1s9RtmN/X9b3r+V03RVUrEUYJSvPdHnOQGTV22P5g5XUQ0D7mQ4obl0+IAgZADYhCvvrbFskIZ5IRbdKnYM6pdSAN19OLj8OKXnyVa+FfBs0QcId0lO1GNoxtOucdiIolzxVeu3zMkacGSOVjYk9ABHV4bQqg99DhqHHzu53e7xoMZDaE/xitgTzErvHhTj2AhCVviwbvqRVnmJQdKDGGfCsarZzsXTNOn19FYvsCCfYEaitj4KJNRFEsV9P4b4f43PQ/7W7quGnSB7IQcHXbu3ixqr/H4hQJa6v13Xq8wzPHGCc0GOGj+RRZDEFVBAeXC6CDx+QpKzz3OOzNvKEEBEeiv6xW8WysNsIwA=}
bot:
  automerge: true
